version: 2
updates:
  - package-ecosystem: maven
    directory: /api
    schedule:
      interval: monthly
    groups:
      maven-minor:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: monthly
    groups:
      web-minor:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: monthly
    groups:
      mobile-minor:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
