minimumReleaseAgeExclude:
  - '@expo/cli@57.0.9'
  - '@expo/metro-config@57.0.6'
  - '@expo/prebuild-config@57.0.8'
  - expo-asset@57.0.6
  - expo-constants@57.0.6
  - expo-modules-autolinking@57.0.8
  - expo-modules-core@57.0.6
  - expo@57.0.7
  - expo-application@57.0.2
  - expo-auth-session@57.0.4
  - expo-image-picker@57.0.5
  - expo-location@57.0.5
  - expo-media-library@57.0.3
  - expo-notifications@57.0.6
  - expo-sharing@57.0.6
